### ISSUE TITLE
The point in sales package are not left aligned

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/mesg.com#148]
The points checkmark and cross are not the same width so the text are not aligned.

![Screen Shot 2019-07-04 at 11 54 16](https://user-images.githubusercontent.com/5823445/60640684-85c07400-9e52-11e9-848f-e547c48e10a3.png)

**Comment by EmmanuelDrouin** [comment]
@NicolasMahe good catch ;)
I will fix this
