### ISSUE TITLE
Contribution button on Brave browser

### ISSUE THREAD

**Issue by EmmanuelDrouin** [mesg-foundation/mesg.com#235]
The button to add a contribution don't work on Brave. It open a blank popup.

**Comment by antho1404** [comment]
Nice catch, it works when the shield is off, typeform probably added new tracking system that are banned by brave shield. Maybe we should fallback to a direct redirection to the page. This issue will probably appear with any ad blocker

**Comment by EmmanuelDrouin** [comment]
Would like to try to see if it's only in Brave or if we have the same problem with other ad blocker.
The problem with a redirection to a direct page is that with the free plan at the end of the form process the user won't be redirected to mesg.com.
So i would like to avoid that.
Let's run some test and think of a solution, this problem probably affect only few people, i will check the analytics to be sure.

**Comment by antho1404** [comment]
Let's also check how many people went through the whole process or even open the popup. If there is not much now it's fine to redirect and we will upgrade to improve conversion when we will have traction here. Of course if the fix is quick then fine but I think it will be hard to fix.

**Comment by EmmanuelDrouin** [comment]
It looks like the button are now working on brave. I will close this issue for now.
