### ISSUE TITLE
Glitch on the animation schema (header section - certains mobile versions)

### ISSUE THREAD

**Issue by EmmanuelDrouin** [mesg-foundation/mesg.com#24]
The animation is glitching on certains type of mobile (Vivo, HTC...), doesn't depend of the browsers that are being use. Otherwise it's works perfectly on almost every devices and browsers.

The issue come from the "ClipPath" i'm using to hide the features when they disappear at the bottom. 

I tried differents solutions to fix the bug (webkit prefix, CSS mask ...) but it doesn't change anything.

Removing the "ClipPath" allows the animation to work perfectly on every devices.

So the solution could be to find a way to hide the features without using a "ClipPath".

**Comment by Graphicsepion** [comment]
Temporary solution is to update the mobile software.
Updating the software fix the problem with the ClipPath.
