### ISSUE TITLE
The website is sometimes showing the 404 on the homepage

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/mesg.com#243]
Sometimes, the website is not able to load something from the blog and it displays a 404 on the homepage:
![Screen_Shot_2020-04-17_at_16 39 04](https://user-images.githubusercontent.com/5823445/79556947-f11ac000-80cb-11ea-9f6b-28dd449dc066.png)

**Comment by EmmanuelDrouin** [comment]
@NicolasMahe can you provide more informations?
Which browser are you using, how many times did this error occurred, is it something related to today or did you got this error before?

Never saw this issue before, it's the first time.

Could be something related to the ghost API.

**Comment by EmmanuelDrouin** [comment]
@NicolasMahe did you encountered this error again recently?

I think it was a one time issue with the Ghost API. 

Let me know so i can close this issue.

**Comment by NicolasMahe** [comment]
seems ok now. it's still very slow to load the first time when not using a VPN, but I guess it's a peering issue with my internet provider and netlify hosting.
