### ISSUE TITLE
Content update

### ISSUE THREAD

**Issue by EmmanuelDrouin** [mesg-foundation/mesg.com#254]
We need to check that the content is up to date regarding the Release of Liteflow and the delisting of the MESG Token

The content should be focus on the MESG Vision, long term possibilities, the products developed by the company, etc.

We don't focus anymore on converting users here.

Don't forget to check every pages (FAQ included) ;)

@williamzmorgan  if you have any question regarding the update of the content, please reach out to @antho1404  ;)

**Comment by williamzmorgan** [comment]
I've made some progress on this, but before finishing, I need some additional clarity from @antho1404 on the extent of the remaining economy within MESG, if any, and what will fuel that.

**Comment by NicolasMahe** [comment]
Something more to remove / update:
- [ ] MESG SDK
It has been moved to liteflow (all the JS libs and CLI) but more tools and docs will come to MESG in order to be able (with difficulty) to build services and processes.

**Comment by antho1404** [comment]
SDK definitely not to remove, the content is ok, we don't talk about the js lib, we do talk about a CLI but MESG has a CLI now that let you do all that (even tho it's a bit more complicated).

Agree on the part that we need to have the doc of these tools on this page, API documentation, CLI documentation, architecture documentation etc...
