### ISSUE TITLE
Disallow POST, PUT, DELETE... requests to https://mesg.com

### ISSUE THREAD

**Issue by ilgooz** [mesg-foundation/mesg.com#45]
Static pages should only response to GET requests.

**Comment by antho1404** [comment]
I have an error 405 (Method Not Allowed) when I try to POST on it (same for the others).

```
➜  ~ curl -X POST -I https://mesg.com
HTTP/2 405
server: nginx/1.14.0
date: Mon, 10 Dec 2018 14:46:04 GMT
content-length: 0
```

**Comment by ilgooz** [comment]
That's odd, I can perform a POST req via Postman and it responses with 200 OK and HTML content.

**Comment by antho1404** [comment]
probably due to some specific rules on nginx for curl so this issue is valid

**Comment by NicolasMahe** [comment]
Every request with `curl` user-agent are delivered by a simple http server.
Every other request are delivered by the vue.js website.

**Comment by NicolasMahe** [comment]
We decide to not support the curl for simplicity
