### ISSUE TITLE
#56 MESG documents links to PDF

### ISSUE THREAD

**Issue by EmmanuelDrouin** [mesg-foundation/mesg.com#59]
Users should be able to click on a document and open in a new tab the pdf.

<img width="845" alt="screenshot 2018-12-28 at 11 37 19" src="https://user-images.githubusercontent.com/15095289/50502846-13329e00-0a95-11e9-82fc-26e029621a78.png">

Actually the links redirect to a 404.

Pull request concerned: https://github.com/mesg-foundation/mesg.com/pull/56

**Comment by antho1404** [comment]
Fixed in the PR #56

**Comment by EmmanuelDrouin** [comment]
great job thanks
