### ISSUE TITLE
Better detection of docker installations

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/mesg.com#80]
We need a better detection of docker installation. It looks like we are only looking for installations from apt in linux but docker can be installed with snap and this lead to two docker installation. We need to find a way to make sure we don't install docker on top of an existing one.

https://stackoverflow.com/questions/53547308/docker-swarm-init-fails-address-already-in-use

```
docker swarm init
Error response from daemon: manager stopped: failed to listen on remote API address: listen tcp 0.0.0.0:2377: bind: address already in use
```

**Comment by krhubert** [comment]
> It looks like we are only looking for installations from apt in linux 

Hum, we don't. We check if docker is available in $PATH and can be executed. The install script checks neither apt nor snap.

**Comment by krhubert** [comment]
yes it is:

```
snap list | grep docker
```

But if docker isn't in command line and if it's in snap then what should we do. also not every system has snap (I guess).

**Comment by NicolasMahe** [comment]
Closing because we will remove the install script
