### ISSUE TITLE
Remove sudo from install script

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/mesg.com#90]
The script should be compatible with folder per os to move the cli in a folder that doesn't require any sudo.

If some system require sudo, then explicitly said why a sudo is needed (`please enter your password to move the bin to path/path`) or output the command to the user so he can run it himself.

**Comment by krhubert** [comment]
Under linux all dirs in `$PATH` requires sudo to move it. Also during installation, this is a normal step to execute `sudo` without any message why it is for - check for example [docker](https://get.docker.com/) or any other installation script

**Comment by NicolasMahe** [comment]
From the docker install ink you provide:
```
if [ "$user" != 'root' ]; then
		if command_exists sudo; then
			sh_c='sudo -E sh -c'
		elif command_exists su; then
			sh_c='su -c'
		else
			cat >&2 <<-'EOF'
			Error: this installer needs the ability to run commands as root.
			We are unable to find either "sudo" or "su" available to make this happen.
			EOF
			exit 1
		fi
	fi
```
there is an error explaining with the command needs sudo.

I just want to add more user-friendliness to our install scripts and cli commands :)

**Comment by krhubert** [comment]
Ok, but there is info that `sudo` wasn't found on the server. There is no message why sudo needs to run. But looking at this we should check if `sudo` exists.

**Comment by NicolasMahe** [comment]
Closing this issue because we will remove the install script when the cli js is released: https://github.com/mesg-foundation/docs/issues/44
