### ISSUE TITLE
Do not start core at the end of installation

### ISSUE THREAD

**Issue by NicolasMahe** [mesg-foundation/mesg.com#91]
The install script should not start the core but display the command to do so.

**Comment by krhubert** [comment]
Why?

Every package manager and install script starts the service after installation (like docker, postgres, etc..)

**Comment by NicolasMahe** [comment]
Docker is a daemon and on linux start on startup.
MESG requires to be started.
User should know how to start mesg core by themself.

At least, the install script should display a mini doc saying something like:
```
to start the core, run `mesg-core start`.
to stop the core, run `mesg-core stop`.
```

We need to show way more in install script and cli what are the useful commands to run in context.
Like the command `service deploy`, that show how to start a service. At the last one that show how to display logs.

**Comment by antho1404** [comment]
I'm not really sure about that too, it's good to have it (re)started by default

**Comment by NicolasMahe** [comment]
Closing this issue because we will remove the install script when the js cli is released: https://github.com/mesg-foundation/docs/issues/44
